"""HardwareAnalogWrite demo - Python side.

All of the PWM work happens on the STM32U585 inside `sketch/sketch.ino`: the
library drives every GPIO of the UNO Q, using the STM32 timers where a pin has
one and a software PWM engine everywhere else.

This Python side exists only so that App Lab recognises the project as a
regular App and keeps the container/board plumbing alive. Open the serial
monitor (`arduino-app-cli monitor`) to watch the sketch report its engines.

If you later want to drive the PWM channels from Python, expose the library
over the Bridge API in the sketch and call it from the loop below.
"""

import time

from arduino.app_utils import App

print("HardwareAnalogWrite demo - PWM is generated by the sketch on the MCU.")


def loop():
    """Called repeatedly by the App framework."""
    time.sleep(10)


App.run(user_loop=loop)
